/********************************************************************************
** Form generated from reading UI file 'ventanaagregar.ui'
**
** Created by: Qt User Interface Compiler version 5.12.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_VENTANAAGREGAR_H
#define UI_VENTANAAGREGAR_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_VentanaAgregar
{
public:
    QWidget *centralwidget;
    QGridLayout *gridLayout;
    QTabWidget *tabWidget;
    QWidget *agregarPais;
    QPushButton *btSalirP;
    QLabel *label;
    QLabel *label_2;
    QTextEdit *txtNombrePais;
    QTextEdit *txtCodPais;
    QPushButton *btAceptarPais;
    QWidget *agregarCiudad;
    QPushButton *btSalirCi;
    QTextEdit *txtCodCiudad;
    QLabel *label_3;
    QLabel *label_4;
    QTextEdit *txtNombreCiudad;
    QLabel *label_5;
    QTextEdit *txtCodPaisCiudad;
    QPushButton *btAceptarCi;
    QWidget *agregarConexion;
    QPushButton *btSalirCo;
    QLabel *label_6;
    QTextEdit *txtCodPaisSalida;
    QLabel *label_7;
    QLabel *label_8;
    QTextEdit *txtCodCiudadSalida;
    QTextEdit *txtCodConexion;
    QLabel *label_9;
    QTextEdit *txtCodPaisDestino;
    QLabel *label_10;
    QTextEdit *txtCodCiudadDestino;
    QPushButton *btAceptarCo;
    QLabel *tz;
    QTextEdit *txtTiempo;
    QLabel *label_11;
    QLabel *tzz;
    QTextEdit *txtPrecio;
    QWidget *agregarTipoTren;
    QPushButton *btSalirTipo;
    QPushButton *btAceptarTipo;
    QTextEdit *txtTipo;
    QLabel *label_12;
    QWidget *agregarTren;
    QLabel *label_13;
    QTextEdit *txtTipoTren;
    QLabel *label_14;
    QTextEdit *txtNombreTren;
    QTextEdit *txtCodigoTren;
    QLabel *label_15;
    QTextEdit *txtNumAsientos;
    QLabel *label_16;
    QLabel *label_17;
    QTextEdit *txtPaisSalidaTren;
    QTextEdit *txtCiudadSalidaTren;
    QLabel *label_18;
    QPushButton *btSalirTren;
    QPushButton *btAceptarTren;
    QWidget *agregarRuta;
    QPushButton *btAceptarRuta;
    QPushButton *btSalirRuta;
    QTextEdit *txtCodTipoRuta;
    QLabel *tz_2;
    QLabel *tzz_2;
    QTextEdit *txtCodTrenRuta;
    QLabel *tzz_3;
    QTextEdit *txtCodRuta;
    QLabel *tzz_4;
    QTextEdit *txtCodPaisSalidaRuta;
    QLabel *tzz_5;
    QTextEdit *txtCodCiudadSalidaRuta;
    QLabel *tzz_6;
    QTextEdit *txtCodPaisDestinoRuta;
    QLabel *tzz_7;
    QTextEdit *txtCodCiudadDestinoRuta;
    QLabel *tzz_8;
    QTextEdit *txtPrecioRuta;
    QWidget *agregarAtraccion;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QPushButton *btSalirAtraccion;
    QPushButton *btAceptarAtraccion;
    QTextEdit *txtCodPaisAtraccion;
    QTextEdit *txtCodCiudadAtraccion;
    QTextEdit *txtCodAtraccion;
    QTextEdit *txtNombreAtraccion;
    QTextEdit *txtPrecioAtraccion;

    void setupUi(QMainWindow *VentanaAgregar)
    {
        if (VentanaAgregar->objectName().isEmpty())
            VentanaAgregar->setObjectName(QString::fromUtf8("VentanaAgregar"));
        VentanaAgregar->resize(600, 440);
        VentanaAgregar->setMinimumSize(QSize(600, 430));
        VentanaAgregar->setMaximumSize(QSize(600, 440));
        VentanaAgregar->setAnimated(true);
        centralwidget = new QWidget(VentanaAgregar);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        gridLayout = new QGridLayout(centralwidget);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        gridLayout->setContentsMargins(10, 10, 10, 10);
        tabWidget = new QTabWidget(centralwidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        QFont font;
        font.setFamily(QString::fromUtf8("HP Simplified Light"));
        font.setPointSize(10);
        tabWidget->setFont(font);
        agregarPais = new QWidget();
        agregarPais->setObjectName(QString::fromUtf8("agregarPais"));
        agregarPais->setCursor(QCursor(Qt::ArrowCursor));
        btSalirP = new QPushButton(agregarPais);
        btSalirP->setObjectName(QString::fromUtf8("btSalirP"));
        btSalirP->setGeometry(QRect(60, 320, 80, 31));
        QFont font1;
        font1.setFamily(QString::fromUtf8("HP Simplified Light"));
        font1.setPointSize(14);
        btSalirP->setFont(font1);
        btSalirP->setCursor(QCursor(Qt::PointingHandCursor));
        label = new QLabel(agregarPais);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(70, 140, 208, 22));
        label->setFont(font1);
        label_2 = new QLabel(agregarPais);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(70, 200, 208, 22));
        label_2->setFont(font1);
        txtNombrePais = new QTextEdit(agregarPais);
        txtNombrePais->setObjectName(QString::fromUtf8("txtNombrePais"));
        txtNombrePais->setGeometry(QRect(290, 140, 171, 31));
        txtCodPais = new QTextEdit(agregarPais);
        txtCodPais->setObjectName(QString::fromUtf8("txtCodPais"));
        txtCodPais->setGeometry(QRect(290, 200, 171, 31));
        btAceptarPais = new QPushButton(agregarPais);
        btAceptarPais->setObjectName(QString::fromUtf8("btAceptarPais"));
        btAceptarPais->setGeometry(QRect(410, 320, 80, 31));
        btAceptarPais->setFont(font1);
        btAceptarPais->setCursor(QCursor(Qt::PointingHandCursor));
        tabWidget->addTab(agregarPais, QString());
        agregarCiudad = new QWidget();
        agregarCiudad->setObjectName(QString::fromUtf8("agregarCiudad"));
        btSalirCi = new QPushButton(agregarCiudad);
        btSalirCi->setObjectName(QString::fromUtf8("btSalirCi"));
        btSalirCi->setGeometry(QRect(10, 340, 80, 31));
        btSalirCi->setFont(font1);
        btSalirCi->setCursor(QCursor(Qt::PointingHandCursor));
        txtCodCiudad = new QTextEdit(agregarCiudad);
        txtCodCiudad->setObjectName(QString::fromUtf8("txtCodCiudad"));
        txtCodCiudad->setGeometry(QRect(290, 130, 171, 31));
        label_3 = new QLabel(agregarCiudad);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(30, 70, 241, 22));
        label_3->setFont(font1);
        label_4 = new QLabel(agregarCiudad);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(30, 130, 232, 22));
        label_4->setFont(font1);
        txtNombreCiudad = new QTextEdit(agregarCiudad);
        txtNombreCiudad->setObjectName(QString::fromUtf8("txtNombreCiudad"));
        txtNombreCiudad->setGeometry(QRect(290, 70, 171, 31));
        label_5 = new QLabel(agregarCiudad);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(30, 180, 401, 22));
        label_5->setFont(font1);
        txtCodPaisCiudad = new QTextEdit(agregarCiudad);
        txtCodPaisCiudad->setObjectName(QString::fromUtf8("txtCodPaisCiudad"));
        txtCodPaisCiudad->setGeometry(QRect(290, 220, 171, 31));
        btAceptarCi = new QPushButton(agregarCiudad);
        btAceptarCi->setObjectName(QString::fromUtf8("btAceptarCi"));
        btAceptarCi->setGeometry(QRect(450, 340, 80, 31));
        btAceptarCi->setFont(font1);
        btAceptarCi->setCursor(QCursor(Qt::PointingHandCursor));
        tabWidget->addTab(agregarCiudad, QString());
        agregarConexion = new QWidget();
        agregarConexion->setObjectName(QString::fromUtf8("agregarConexion"));
        btSalirCo = new QPushButton(agregarConexion);
        btSalirCo->setObjectName(QString::fromUtf8("btSalirCo"));
        btSalirCo->setGeometry(QRect(10, 340, 80, 31));
        btSalirCo->setFont(font1);
        btSalirCo->setCursor(QCursor(Qt::PointingHandCursor));
        label_6 = new QLabel(agregarConexion);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(20, 90, 301, 22));
        label_6->setFont(font1);
        txtCodPaisSalida = new QTextEdit(agregarConexion);
        txtCodPaisSalida->setObjectName(QString::fromUtf8("txtCodPaisSalida"));
        txtCodPaisSalida->setGeometry(QRect(370, 40, 171, 31));
        label_7 = new QLabel(agregarConexion);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(20, 40, 270, 22));
        label_7->setFont(font1);
        label_8 = new QLabel(agregarConexion);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(20, 140, 251, 22));
        label_8->setFont(font1);
        txtCodCiudadSalida = new QTextEdit(agregarConexion);
        txtCodCiudadSalida->setObjectName(QString::fromUtf8("txtCodCiudadSalida"));
        txtCodCiudadSalida->setGeometry(QRect(370, 90, 171, 31));
        txtCodConexion = new QTextEdit(agregarConexion);
        txtCodConexion->setObjectName(QString::fromUtf8("txtCodConexion"));
        txtCodConexion->setGeometry(QRect(370, 140, 171, 31));
        label_9 = new QLabel(agregarConexion);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(20, 190, 283, 22));
        label_9->setFont(font1);
        txtCodPaisDestino = new QTextEdit(agregarConexion);
        txtCodPaisDestino->setObjectName(QString::fromUtf8("txtCodPaisDestino"));
        txtCodPaisDestino->setGeometry(QRect(370, 190, 171, 31));
        label_10 = new QLabel(agregarConexion);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(20, 240, 316, 22));
        label_10->setFont(font1);
        txtCodCiudadDestino = new QTextEdit(agregarConexion);
        txtCodCiudadDestino->setObjectName(QString::fromUtf8("txtCodCiudadDestino"));
        txtCodCiudadDestino->setGeometry(QRect(370, 240, 171, 31));
        btAceptarCo = new QPushButton(agregarConexion);
        btAceptarCo->setObjectName(QString::fromUtf8("btAceptarCo"));
        btAceptarCo->setGeometry(QRect(470, 340, 80, 31));
        btAceptarCo->setFont(font1);
        btAceptarCo->setCursor(QCursor(Qt::PointingHandCursor));
        tz = new QLabel(agregarConexion);
        tz->setObjectName(QString::fromUtf8("tz"));
        tz->setGeometry(QRect(22, 292, 64, 22));
        tz->setFont(font1);
        txtTiempo = new QTextEdit(agregarConexion);
        txtTiempo->setObjectName(QString::fromUtf8("txtTiempo"));
        txtTiempo->setGeometry(QRect(92, 292, 70, 31));
        label_11 = new QLabel(agregarConexion);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(168, 292, 18, 22));
        QFont font2;
        font2.setPointSize(14);
        label_11->setFont(font2);
        tzz = new QLabel(agregarConexion);
        tzz->setObjectName(QString::fromUtf8("tzz"));
        tzz->setGeometry(QRect(220, 292, 51, 22));
        tzz->setFont(font1);
        txtPrecio = new QTextEdit(agregarConexion);
        txtPrecio->setObjectName(QString::fromUtf8("txtPrecio"));
        txtPrecio->setGeometry(QRect(280, 292, 70, 31));
        tabWidget->addTab(agregarConexion, QString());
        agregarTipoTren = new QWidget();
        agregarTipoTren->setObjectName(QString::fromUtf8("agregarTipoTren"));
        btSalirTipo = new QPushButton(agregarTipoTren);
        btSalirTipo->setObjectName(QString::fromUtf8("btSalirTipo"));
        btSalirTipo->setGeometry(QRect(10, 330, 80, 31));
        btSalirTipo->setFont(font1);
        btSalirTipo->setCursor(QCursor(Qt::PointingHandCursor));
        btAceptarTipo = new QPushButton(agregarTipoTren);
        btAceptarTipo->setObjectName(QString::fromUtf8("btAceptarTipo"));
        btAceptarTipo->setGeometry(QRect(480, 330, 80, 31));
        btAceptarTipo->setFont(font1);
        btAceptarTipo->setCursor(QCursor(Qt::PointingHandCursor));
        txtTipo = new QTextEdit(agregarTipoTren);
        txtTipo->setObjectName(QString::fromUtf8("txtTipo"));
        txtTipo->setGeometry(QRect(340, 170, 137, 31));
        label_12 = new QLabel(agregarTipoTren);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(30, 170, 256, 22));
        label_12->setFont(font1);
        tabWidget->addTab(agregarTipoTren, QString());
        agregarTren = new QWidget();
        agregarTren->setObjectName(QString::fromUtf8("agregarTren"));
        label_13 = new QLabel(agregarTren);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(30, 50, 256, 22));
        label_13->setFont(font1);
        txtTipoTren = new QTextEdit(agregarTren);
        txtTipoTren->setObjectName(QString::fromUtf8("txtTipoTren"));
        txtTipoTren->setGeometry(QRect(380, 50, 137, 29));
        label_14 = new QLabel(agregarTren);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(30, 100, 199, 22));
        label_14->setFont(font1);
        txtNombreTren = new QTextEdit(agregarTren);
        txtNombreTren->setObjectName(QString::fromUtf8("txtNombreTren"));
        txtNombreTren->setGeometry(QRect(380, 150, 137, 29));
        txtCodigoTren = new QTextEdit(agregarTren);
        txtCodigoTren->setObjectName(QString::fromUtf8("txtCodigoTren"));
        txtCodigoTren->setGeometry(QRect(380, 100, 137, 29));
        label_15 = new QLabel(agregarTren);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(30, 150, 208, 22));
        label_15->setFont(font1);
        txtNumAsientos = new QTextEdit(agregarTren);
        txtNumAsientos->setObjectName(QString::fromUtf8("txtNumAsientos"));
        txtNumAsientos->setGeometry(QRect(380, 200, 137, 29));
        label_16 = new QLabel(agregarTren);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(30, 200, 295, 22));
        label_16->setFont(font1);
        label_17 = new QLabel(agregarTren);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(30, 250, 262, 22));
        label_17->setFont(font1);
        txtPaisSalidaTren = new QTextEdit(agregarTren);
        txtPaisSalidaTren->setObjectName(QString::fromUtf8("txtPaisSalidaTren"));
        txtPaisSalidaTren->setGeometry(QRect(380, 250, 137, 29));
        txtCiudadSalidaTren = new QTextEdit(agregarTren);
        txtCiudadSalidaTren->setObjectName(QString::fromUtf8("txtCiudadSalidaTren"));
        txtCiudadSalidaTren->setGeometry(QRect(380, 300, 137, 29));
        label_18 = new QLabel(agregarTren);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(30, 300, 299, 22));
        label_18->setFont(font1);
        btSalirTren = new QPushButton(agregarTren);
        btSalirTren->setObjectName(QString::fromUtf8("btSalirTren"));
        btSalirTren->setGeometry(QRect(30, 340, 80, 31));
        btSalirTren->setFont(font1);
        btSalirTren->setCursor(QCursor(Qt::PointingHandCursor));
        btAceptarTren = new QPushButton(agregarTren);
        btAceptarTren->setObjectName(QString::fromUtf8("btAceptarTren"));
        btAceptarTren->setGeometry(QRect(470, 340, 80, 31));
        btAceptarTren->setFont(font1);
        btAceptarTren->setCursor(QCursor(Qt::PointingHandCursor));
        tabWidget->addTab(agregarTren, QString());
        agregarRuta = new QWidget();
        agregarRuta->setObjectName(QString::fromUtf8("agregarRuta"));
        btAceptarRuta = new QPushButton(agregarRuta);
        btAceptarRuta->setObjectName(QString::fromUtf8("btAceptarRuta"));
        btAceptarRuta->setGeometry(QRect(480, 350, 80, 31));
        btAceptarRuta->setFont(font1);
        btAceptarRuta->setCursor(QCursor(Qt::PointingHandCursor));
        btSalirRuta = new QPushButton(agregarRuta);
        btSalirRuta->setObjectName(QString::fromUtf8("btSalirRuta"));
        btSalirRuta->setGeometry(QRect(10, 350, 80, 31));
        btSalirRuta->setFont(font1);
        btSalirRuta->setCursor(QCursor(Qt::PointingHandCursor));
        txtCodTipoRuta = new QTextEdit(agregarRuta);
        txtCodTipoRuta->setObjectName(QString::fromUtf8("txtCodTipoRuta"));
        txtCodTipoRuta->setGeometry(QRect(390, 10, 140, 31));
        tz_2 = new QLabel(agregarRuta);
        tz_2->setObjectName(QString::fromUtf8("tz_2"));
        tz_2->setGeometry(QRect(30, 10, 256, 22));
        tz_2->setFont(font1);
        tzz_2 = new QLabel(agregarRuta);
        tzz_2->setObjectName(QString::fromUtf8("tzz_2"));
        tzz_2->setGeometry(QRect(30, 60, 195, 22));
        tzz_2->setFont(font1);
        txtCodTrenRuta = new QTextEdit(agregarRuta);
        txtCodTrenRuta->setObjectName(QString::fromUtf8("txtCodTrenRuta"));
        txtCodTrenRuta->setGeometry(QRect(390, 60, 140, 31));
        tzz_3 = new QLabel(agregarRuta);
        tzz_3->setObjectName(QString::fromUtf8("tzz_3"));
        tzz_3->setGeometry(QRect(30, 110, 208, 22));
        tzz_3->setFont(font1);
        txtCodRuta = new QTextEdit(agregarRuta);
        txtCodRuta->setObjectName(QString::fromUtf8("txtCodRuta"));
        txtCodRuta->setGeometry(QRect(390, 110, 140, 31));
        tzz_4 = new QLabel(agregarRuta);
        tzz_4->setObjectName(QString::fromUtf8("tzz_4"));
        tzz_4->setGeometry(QRect(30, 160, 266, 22));
        tzz_4->setFont(font1);
        txtCodPaisSalidaRuta = new QTextEdit(agregarRuta);
        txtCodPaisSalidaRuta->setObjectName(QString::fromUtf8("txtCodPaisSalidaRuta"));
        txtCodPaisSalidaRuta->setGeometry(QRect(390, 160, 140, 31));
        tzz_5 = new QLabel(agregarRuta);
        tzz_5->setObjectName(QString::fromUtf8("tzz_5"));
        tzz_5->setGeometry(QRect(30, 210, 299, 22));
        tzz_5->setFont(font1);
        txtCodCiudadSalidaRuta = new QTextEdit(agregarRuta);
        txtCodCiudadSalidaRuta->setObjectName(QString::fromUtf8("txtCodCiudadSalidaRuta"));
        txtCodCiudadSalidaRuta->setGeometry(QRect(390, 210, 140, 31));
        tzz_6 = new QLabel(agregarRuta);
        tzz_6->setObjectName(QString::fromUtf8("tzz_6"));
        tzz_6->setGeometry(QRect(30, 260, 279, 22));
        tzz_6->setFont(font1);
        txtCodPaisDestinoRuta = new QTextEdit(agregarRuta);
        txtCodPaisDestinoRuta->setObjectName(QString::fromUtf8("txtCodPaisDestinoRuta"));
        txtCodPaisDestinoRuta->setGeometry(QRect(390, 260, 140, 31));
        tzz_7 = new QLabel(agregarRuta);
        tzz_7->setObjectName(QString::fromUtf8("tzz_7"));
        tzz_7->setGeometry(QRect(30, 310, 312, 22));
        tzz_7->setFont(font1);
        txtCodCiudadDestinoRuta = new QTextEdit(agregarRuta);
        txtCodCiudadDestinoRuta->setObjectName(QString::fromUtf8("txtCodCiudadDestinoRuta"));
        txtCodCiudadDestinoRuta->setGeometry(QRect(390, 310, 140, 31));
        tzz_8 = new QLabel(agregarRuta);
        tzz_8->setObjectName(QString::fromUtf8("tzz_8"));
        tzz_8->setGeometry(QRect(170, 350, 51, 22));
        tzz_8->setFont(font1);
        txtPrecioRuta = new QTextEdit(agregarRuta);
        txtPrecioRuta->setObjectName(QString::fromUtf8("txtPrecioRuta"));
        txtPrecioRuta->setGeometry(QRect(235, 348, 70, 31));
        tabWidget->addTab(agregarRuta, QString());
        agregarAtraccion = new QWidget();
        agregarAtraccion->setObjectName(QString::fromUtf8("agregarAtraccion"));
        label_19 = new QLabel(agregarAtraccion);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(20, 240, 260, 22));
        label_19->setFont(font1);
        label_20 = new QLabel(agregarAtraccion);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(20, 100, 232, 22));
        label_20->setFont(font1);
        label_21 = new QLabel(agregarAtraccion);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(20, 30, 420, 22));
        label_21->setFont(font1);
        label_22 = new QLabel(agregarAtraccion);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(20, 170, 251, 22));
        label_22->setFont(font1);
        label_23 = new QLabel(agregarAtraccion);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(20, 300, 246, 22));
        label_23->setFont(font1);
        btSalirAtraccion = new QPushButton(agregarAtraccion);
        btSalirAtraccion->setObjectName(QString::fromUtf8("btSalirAtraccion"));
        btSalirAtraccion->setGeometry(QRect(10, 350, 80, 31));
        btSalirAtraccion->setFont(font1);
        btSalirAtraccion->setCursor(QCursor(Qt::PointingHandCursor));
        btAceptarAtraccion = new QPushButton(agregarAtraccion);
        btAceptarAtraccion->setObjectName(QString::fromUtf8("btAceptarAtraccion"));
        btAceptarAtraccion->setGeometry(QRect(480, 350, 80, 31));
        btAceptarAtraccion->setFont(font1);
        btAceptarAtraccion->setCursor(QCursor(Qt::PointingHandCursor));
        txtCodPaisAtraccion = new QTextEdit(agregarAtraccion);
        txtCodPaisAtraccion->setObjectName(QString::fromUtf8("txtCodPaisAtraccion"));
        txtCodPaisAtraccion->setGeometry(QRect(410, 60, 140, 31));
        txtCodCiudadAtraccion = new QTextEdit(agregarAtraccion);
        txtCodCiudadAtraccion->setObjectName(QString::fromUtf8("txtCodCiudadAtraccion"));
        txtCodCiudadAtraccion->setGeometry(QRect(410, 120, 140, 31));
        txtCodAtraccion = new QTextEdit(agregarAtraccion);
        txtCodAtraccion->setObjectName(QString::fromUtf8("txtCodAtraccion"));
        txtCodAtraccion->setGeometry(QRect(410, 180, 140, 31));
        txtNombreAtraccion = new QTextEdit(agregarAtraccion);
        txtNombreAtraccion->setObjectName(QString::fromUtf8("txtNombreAtraccion"));
        txtNombreAtraccion->setGeometry(QRect(410, 240, 140, 31));
        txtPrecioAtraccion = new QTextEdit(agregarAtraccion);
        txtPrecioAtraccion->setObjectName(QString::fromUtf8("txtPrecioAtraccion"));
        txtPrecioAtraccion->setGeometry(QRect(410, 300, 140, 31));
        tabWidget->addTab(agregarAtraccion, QString());

        gridLayout->addWidget(tabWidget, 0, 0, 1, 1);

        VentanaAgregar->setCentralWidget(centralwidget);

        retranslateUi(VentanaAgregar);
        QObject::connect(btSalirRuta, SIGNAL(clicked()), VentanaAgregar, SLOT(close()));
        QObject::connect(btSalirTren, SIGNAL(clicked()), VentanaAgregar, SLOT(close()));
        QObject::connect(btSalirTipo, SIGNAL(clicked()), VentanaAgregar, SLOT(close()));
        QObject::connect(btSalirCo, SIGNAL(clicked()), VentanaAgregar, SLOT(close()));
        QObject::connect(btSalirCi, SIGNAL(clicked()), VentanaAgregar, SLOT(close()));
        QObject::connect(btSalirP, SIGNAL(clicked()), VentanaAgregar, SLOT(close()));
        QObject::connect(btSalirAtraccion, SIGNAL(clicked()), VentanaAgregar, SLOT(close()));

        tabWidget->setCurrentIndex(6);


        QMetaObject::connectSlotsByName(VentanaAgregar);
    } // setupUi

    void retranslateUi(QMainWindow *VentanaAgregar)
    {
        VentanaAgregar->setWindowTitle(QApplication::translate("VentanaAgregar", "Agregar", nullptr));
        btSalirP->setText(QApplication::translate("VentanaAgregar", "Salir", nullptr));
        label->setText(QApplication::translate("VentanaAgregar", "Ingrese el nombre del pa\303\255s: ", nullptr));
        label_2->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo del pa\303\255s: ", nullptr));
        btAceptarPais->setText(QApplication::translate("VentanaAgregar", "Aceptar", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(agregarPais), QApplication::translate("VentanaAgregar", "Pais", nullptr));
        btSalirCi->setText(QApplication::translate("VentanaAgregar", "Salir", nullptr));
        label_3->setText(QApplication::translate("VentanaAgregar", "Ingrese el nombre de la ciudad: ", nullptr));
        label_4->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo de la ciudad: ", nullptr));
        label_5->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo del pa\303\255s al que pertenece la ciudad: ", nullptr));
        btAceptarCi->setText(QApplication::translate("VentanaAgregar", "Aceptar", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(agregarCiudad), QApplication::translate("VentanaAgregar", "Ciudad", nullptr));
        btSalirCo->setText(QApplication::translate("VentanaAgregar", "Salir", nullptr));
        label_6->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo de la ciudad de salida: ", nullptr));
        label_7->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo del pa\303\255s de salida: ", nullptr));
        label_8->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo de la conexi\303\263n: ", nullptr));
        label_9->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo del pa\303\255s de destino: ", nullptr));
        label_10->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo de la ciudad de destino: ", nullptr));
        btAceptarCo->setText(QApplication::translate("VentanaAgregar", "Aceptar", nullptr));
        tz->setText(QApplication::translate("VentanaAgregar", "Tiempo:", nullptr));
        label_11->setText(QApplication::translate("VentanaAgregar", "hr.", nullptr));
        tzz->setText(QApplication::translate("VentanaAgregar", "Precio:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(agregarConexion), QApplication::translate("VentanaAgregar", "Conexi\303\263n", nullptr));
        btSalirTipo->setText(QApplication::translate("VentanaAgregar", "Salir", nullptr));
        btAceptarTipo->setText(QApplication::translate("VentanaAgregar", "Aceptar", nullptr));
        label_12->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo del tipo de tren: ", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(agregarTipoTren), QApplication::translate("VentanaAgregar", "Tipo de Tren", nullptr));
        label_13->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo del tipo de tren: ", nullptr));
        label_14->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo del tren: ", nullptr));
        label_15->setText(QApplication::translate("VentanaAgregar", "Ingrese el nombre del tren: ", nullptr));
        label_16->setText(QApplication::translate("VentanaAgregar", "Ingrese el n\303\272mero de asientos del tren:", nullptr));
        label_17->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo de pa\303\255s de salida:", nullptr));
        label_18->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo de la ciudad de salida:", nullptr));
        btSalirTren->setText(QApplication::translate("VentanaAgregar", "Salir", nullptr));
        btAceptarTren->setText(QApplication::translate("VentanaAgregar", "Aceptar", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(agregarTren), QApplication::translate("VentanaAgregar", "Tren", nullptr));
        btAceptarRuta->setText(QApplication::translate("VentanaAgregar", "Aceptar", nullptr));
        btSalirRuta->setText(QApplication::translate("VentanaAgregar", "Salir", nullptr));
        tz_2->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo del tipo de tren: ", nullptr));
        tzz_2->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo del tren:", nullptr));
        tzz_3->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo de la ruta:", nullptr));
        tzz_4->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo del pais de salida:", nullptr));
        tzz_5->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo de la ciudad de salida:", nullptr));
        tzz_6->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo del pais de destino:", nullptr));
        tzz_7->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo de la ciudad de destino:", nullptr));
        tzz_8->setText(QApplication::translate("VentanaAgregar", "Precio:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(agregarRuta), QApplication::translate("VentanaAgregar", "Ruta", nullptr));
        label_19->setText(QApplication::translate("VentanaAgregar", "Ingrese el nombre de la atracci\303\263n: ", nullptr));
        label_20->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo de la ciudad: ", nullptr));
        label_21->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo del pa\303\255s al que pertenece la atracci\303\263n: ", nullptr));
        label_22->setText(QApplication::translate("VentanaAgregar", "Ingrese el c\303\263digo de la atracci\303\263n: ", nullptr));
        label_23->setText(QApplication::translate("VentanaAgregar", "Ingrese el precio de la atracci\303\263n: ", nullptr));
        btSalirAtraccion->setText(QApplication::translate("VentanaAgregar", "Salir", nullptr));
        btAceptarAtraccion->setText(QApplication::translate("VentanaAgregar", "Aceptar", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(agregarAtraccion), QApplication::translate("VentanaAgregar", "Atracci\303\263n", nullptr));
    } // retranslateUi

};

namespace Ui {
    class VentanaAgregar: public Ui_VentanaAgregar {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_VENTANAAGREGAR_H
